### ISSUE TITLE
"serverless"?? )))))))

### ISSUE THREAD

**Issue by Zeipt** [anaibol/awesome-serverless#1]
Amazon AWS is serverless? Or Firebase?

**Comment by anaibol** [comment]
Amazon provides a service called Lambda that consist on running functions, snippets of code on the cloud. Firebase provide also cloud services, but it's not the same.

**Comment by Zeipt** [comment]
And clouds are not servers? Ooook..

**Comment by anaibol** [comment]
"Lambda allows you to NOT think about servers. Which means you no longer have to deal with over/under capacity, deployments, scaling and fault tolerance, OS or language updates, metrics, and logging."

https://www.quora.com/What-is-Serverless-Computing

**Comment by Zeipt** [comment]
Oh, I see. So, "serverless" is just "mass surveillance" promo...

**Comment by anaibol** [comment]
Thinking that way you could consider also "mass surveillance" Github, Facebook, Twitter and all the Internet.

**Comment by Zeipt** [comment]
So, are you trying to say that Facebook, Twitter is not "mass surveillance"? Guy, I hoped that you are more IT experienced.. Sorry for time)) Good luck.
