### ISSUE TITLE
Does the public domain license apply to the image?

### ISSUE THREAD

**Issue by jvhellemond** [anaibol/awesome-serverless#21]
I really like the image used in your `README.md`. Does the public domain license (nice!) apply to the image as well? I would like to use it as a background image for our [Serverless Amsterdam meetup group](https://serverless.amsterdam/).

**Comment by anaibol** [comment]
Hi! I am sorry but I really don't think so, I found it on google images, but not sure that it's a "free" image.
You have many similar images doing this search:
https://www.google.fr/search?sa=G&hl=en-FR&tbs=simg:CAES5gEJqMjjScJaVYIa2gELEKjU2AQaBAgBCAkMCxCwjKcIGmIKYAgDEijxBsADvQHhAc4SugKjCrwB4gjGA7oomj3_1M8A9vj2hNLsosj3BPaM0GjBQ4D94j_1AH6plBpsjIgGSsVm8qEUqpb9a5K79IwLhIujImunJFDSgxhXt7k9c_1kt0gAwwLEI6u_1ggaCgoICAESBJ3MgOEMCxCd7cEJGkYKCAoGY2lyY2xlCg8KDWNvbXB1dGVyIGljb24KDwoNY29tbXVuaWNhdGlvbgoMCgptdWx0aW1lZGlhCgoKCGdyYXBoaWNzDA&q=server+flat&tbm=isch&ved=0ahUKEwj3_frhi9zNAhWBFxQKHd6-DeUQsw4IIQ&biw=1920&bih=964 but you would have to buy one or check if it's a free one.

Cheers and good luck!

**Comment by jvhellemond** [comment]
Hi, thanks for your comment. I assumed it was an original artwork, haven't seen it anywhere else. I'll keep looking.
